### PR TITLE
New structure for translations

### PR DESCRIPTION
**Pull request by Alkarex**
https://github.com/Deevad/peppercarrot_print_book/issues/4
And new script to initialize a new language

### CODE REVIEW

**Comment by Alkarex** [comment]
@Deevad You can give it a try with:
```sh
./initLang.bash fr
./getPages.bash fr
```

**Comment by Deevad** [comment]
Oh Super! Thank you!

On my side I spent the day to merge the 23 git episode : https://framagit.org/peppercarrot/webcomics ; it's still WIP but it's taking shape. I'll review the change and I'll be back in 5 min.

**Comment by Alkarex** [comment]
@Deevad Is the naming `pages/gfx_*` on purpose instead of `pages/en_*`?

```xml
<PAGEOBJECT PFILE="pages/gfx_Pepper-and-Carrot_by-David-Revoy_E01P01.jpg" />
```

https://github.com/Deevad/peppercarrot_print_book/blob/bc27c50df5914a21f5362c8c93fdf578bf613e66/B01_C_main-pages.sla#L160

**Comment by Deevad** [comment]
Yes @Alkarex ; for many pages;  I use the 'gfx_' ( the version without text ) to clean/mask the end of the episode and hide credit with various font size at the end.

**Comment by Deevad** [comment]
The script looks super useful!

What are the change in the *.sla ?

**Comment by Alkarex** [comment]
The changes in `*.sla` are the step 2 of https://github.com/Deevad/peppercarrot_print_book/issues/4#issuecomment-342017647 :-)

**Comment by Deevad** [comment]
Thank you!

**Pull request merged**
